### ISSUE TITLE
Tabelle history fehlt

### ISSUE THREAD

**Issue by Auer83** [druckgott/rc-flight-planning#1]
Hallo,

habe das Tool erst jetzt entdeckt und installiert, aber leider bekomme ich keine Zeitenanzeige.
Beim Durchsehen ist mir aufgefallen, dass mit der flugtag_2017.sql keine Tabelle "history" erzeugt wird.

Schöne Grüße,

Karl Heinz

**Comment by druckgott** [comment]
ist geupdated.
